// AUTO-GENERATED by scripts/generate-web-embed.ts. Do not edit by hand.
// Regenerate with: bun scripts/generate-web-embed.ts (after `bun run web:build`).
//
// Each entry imports a file with `with { type: "file" }` so Bun embeds the
// bytes into the compiled binary; `file` is a runtime-resolvable path that
// Bun.file() can read both in dev and inside the single-file executable.
//
// The committed version is intentionally EMPTY: hashed asset names only exist
// after a web build, so a populated manifest would break fresh checkouts and
// `tsc`. build-release.ts populates it right before the compile step, then
// resets it to empty (`--empty`) so the working tree stays clean.

import _a0 from "../web/dist/assets/index-B7kBhUNi.js" with { type: 'file' };
import _a1 from "../web/dist/assets/index-Boppht66.css" with { type: 'file' };
import _a2 from "../web/dist/index.html" with { type: 'file' };
import _a3 from "../web/dist/manifest.webmanifest" with { type: 'file' };
import _a4 from "../web/dist/sw.js" with { type: 'file' };

export interface EmbeddedAsset { route: string; file: string }

export const embeddedAssets: EmbeddedAsset[] = [
  { route: "/assets/index-B7kBhUNi.js", file: _a0 },
  { route: "/assets/index-Boppht66.css", file: _a1 },
  { route: "/index.html", file: _a2 },
  { route: "/manifest.webmanifest", file: _a3 },
  { route: "/sw.js", file: _a4 },
];
