// AUTO-GENERATED by scripts/generate-web-embed.ts. Do not edit by hand.
// Regenerate with: bun scripts/generate-web-embed.ts (after `bun run web:build`).
//
// Each entry imports a file with `with { type: "file" }` so Bun embeds the
// bytes into the compiled binary; `file` is a runtime-resolvable path that
// Bun.file() can read both in dev and inside the single-file executable.
//
// The committed version is intentionally EMPTY: hashed asset names only exist
// after a web build, so a populated manifest would break fresh checkouts and
// `tsc`. build-release.ts populates it right before the compile step, then
// resets it to empty (`--empty`) so the working tree stays clean.

export interface EmbeddedAsset { route: string; file: string }
export const embeddedAssets: EmbeddedAsset[] = [];
