#!/usr/bin/env bun
/**
 * Generate server/web-assets.generated.ts from the built web/dist bundle.
 *
 * Why: `bun build --compile server/server.ts` produces a single-file binary,
 * but the server historically served the UI from the web/dist *directory* on
 * disk (serveStatic). A standalone downloaded binary has no web/dist beside it,
 * so it showed "web bundle is not built". This generator emits a module that
 * imports every file in web/dist with `with { type: "file" }`, which Bun embeds
 * directly into the compiled binary. The server then serves those embedded
 * assets, so a single downloaded exe works with zero extra files.
 *
 * Run after `bun run web:build` and before the compile step. build-release.ts
 * calls this automatically; you can also run it directly:
 *   bun scripts/generate-web-embed.ts
 *
 * If web/dist is missing/empty, it writes an empty manifest (dev mode falls
 * back to filesystem serveStatic / the dev stub).
 */

import { readdir, writeFile, stat } from 'fs/promises';
import { existsSync } from 'fs';
import { resolve, join, relative } from 'path';

const PROJECT_ROOT = resolve(import.meta.dir, '..');
const DIST_DIR = join(PROJECT_ROOT, 'web', 'dist');
const OUT_FILE = join(PROJECT_ROOT, 'server', 'web-assets.generated.ts');

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (e.isFile()) {
      files.push(full);
    }
  }
  return files;
}

/** POSIX-style path for use in import specifiers (Bun requires forward slashes). */
function toImportSpecifier(absFile: string): string {
  // Relative to the generated file's directory (server/).
  const fromDir = join(PROJECT_ROOT, 'server');
  let rel = relative(fromDir, absFile).split('\\').join('/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

/** HTTP route for an asset, e.g. web/dist/assets/x.js -> /assets/x.js */
function toRoute(absFile: string): string {
  const rel = relative(DIST_DIR, absFile).split('\\').join('/');
  return '/' + rel;
}

const EMPTY_MANIFEST_BODY =
  'export interface EmbeddedAsset { route: string; file: string }\n' +
  'export const embeddedAssets: EmbeddedAsset[] = [];\n';

async function main(): Promise<void> {
  const banner =
    '// AUTO-GENERATED by scripts/generate-web-embed.ts. Do not edit by hand.\n' +
    '// Regenerate with: bun scripts/generate-web-embed.ts (after `bun run web:build`).\n' +
    '//\n' +
    '// Each entry imports a file with `with { type: "file" }` so Bun embeds the\n' +
    '// bytes into the compiled binary; `file` is a runtime-resolvable path that\n' +
    '// Bun.file() can read both in dev and inside the single-file executable.\n' +
    '//\n' +
    '// The committed version is intentionally EMPTY: hashed asset names only exist\n' +
    '// after a web build, so a populated manifest would break fresh checkouts and\n' +
    '// `tsc`. build-release.ts populates it right before the compile step, then\n' +
    '// resets it to empty (`--empty`) so the working tree stays clean.\n\n';

  // --empty: write the committed (empty) form regardless of web/dist contents.
  if (process.argv.slice(2).includes('--empty')) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] wrote empty manifest (--empty)\n`);
    return;
  }

  if (!existsSync(DIST_DIR) || !(await stat(DIST_DIR)).isDirectory()) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] web/dist not found — wrote empty manifest\n`);
    return;
  }

  const files = (await walk(DIST_DIR)).sort();
  if (files.length === 0) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] web/dist empty — wrote empty manifest\n`);
    return;
  }

  const importLines: string[] = [];
  const entryLines: string[] = [];
  files.forEach((f, i) => {
    const spec = toImportSpecifier(f);
    const route = toRoute(f);
    importLines.push(`import _a${i} from ${JSON.stringify(spec)} with { type: 'file' };`);
    entryLines.push(`  { route: ${JSON.stringify(route)}, file: _a${i} },`);
  });

  const out =
    banner +
    importLines.join('\n') +
    '\n\n' +
    'export interface EmbeddedAsset { route: string; file: string }\n\n' +
    'export const embeddedAssets: EmbeddedAsset[] = [\n' +
    entryLines.join('\n') +
    '\n];\n';

  await writeFile(OUT_FILE, out);
  process.stdout.write(
    `[generate-web-embed] embedded ${files.length} file(s) from web/dist -> server/web-assets.generated.ts\n`,
  );
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  process.stderr.write(`generate-web-embed failed: ${msg}\n`);
  process.exit(1);
});
