#!/usr/bin/env bun
/**
 * Generate server/web-assets.generated.ts from the built web/dist bundle.
 *
 * Why: `bun build --compile server/server.ts` produces a single-file binary,
 * but the server historically served the UI from the web/dist *directory* on
 * disk (serveStatic). A standalone downloaded binary has no web/dist beside it,
 * so it showed "web bundle is not built". This generator emits a module that
 * imports every file in web/dist with `with { type: "file" }`, which Bun embeds
 * directly into the compiled binary. The server then serves those embedded
 * assets, so a single downloaded exe works with zero extra files.
 *
 * Run after `bun run web:build` and before the compile step. build-release.ts
 * calls this automatically; you can also run it directly:
 *   bun scripts/generate-web-embed.ts
 *
 * If web/dist is missing/empty, it writes an empty manifest (dev mode falls
 * back to filesystem serveStatic / the dev stub).
 *
 * REL-03 / #103: never embed sourcemaps (*.map), dotfiles, or non-allowlisted
 * extensions — those can bake absolute host paths + full source into release
 * binaries (PII / IP leak).
 */

import { readdir, writeFile, stat } from 'fs/promises';
import { existsSync } from 'fs';
import { resolve, join, relative, basename, extname } from 'path';

const PROJECT_ROOT = resolve(import.meta.dir, '..');
const DIST_DIR = join(PROJECT_ROOT, 'web', 'dist');
const OUT_FILE = join(PROJECT_ROOT, 'server', 'web-assets.generated.ts');

/** Extensions safe to ship inside a release binary (REL-03 allowlist). */
export const EMBED_ALLOWED_EXTENSIONS = new Set([
  '.html',
  '.js',
  '.css',
  '.svg',
  '.png',
  '.ico',
  '.woff',
  '.woff2',
  '.json',
  '.webmanifest',
  '.txt', // e.g. robots.txt if present
]);

/**
 * Decide whether a file under web/dist should be embedded.
 * Rejects: sourcemaps, any dotfile (name or path segment), non-allowlisted ext.
 */
export function shouldEmbedAsset(absFile: string, distDir: string = DIST_DIR): boolean {
  const rel = relative(distDir, absFile).split('\\').join('/');
  if (!rel || rel.startsWith('..')) return false;

  const parts = rel.split('/');
  if (parts.some((p) => p.startsWith('.'))) return false;

  const base = basename(rel);
  if (base.startsWith('.')) return false;

  const ext = extname(base).toLowerCase();
  if (ext === '.map') return false;
  if (!EMBED_ALLOWED_EXTENSIONS.has(ext)) return false;

  return true;
}

/** True if any path is a sourcemap (used for strict release fail). */
export function hasSourcemapFiles(files: string[]): boolean {
  return files.some((f) => extname(f).toLowerCase() === '.map' || f.toLowerCase().endsWith('.js.map'));
}

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      // Skip hidden directories entirely (.git, .DS_Store folders, etc.)
      if (e.name.startsWith('.')) continue;
      files.push(...(await walk(full)));
    } else if (e.isFile()) {
      files.push(full);
    }
  }
  return files;
}

/** POSIX-style path for use in import specifiers (Bun requires forward slashes). */
function toImportSpecifier(absFile: string): string {
  // Relative to the generated file's directory (server/).
  const fromDir = join(PROJECT_ROOT, 'server');
  let rel = relative(fromDir, absFile).split('\\').join('/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

/** HTTP route for an asset, e.g. web/dist/assets/x.js -> /assets/x.js */
function toRoute(absFile: string): string {
  const rel = relative(DIST_DIR, absFile).split('\\').join('/');
  return '/' + rel;
}

const EMPTY_MANIFEST_BODY =
  'export interface EmbeddedAsset { route: string; file: string }\n' +
  'export const embeddedAssets: EmbeddedAsset[] = [];\n';

export async function main(argv: string[] = process.argv.slice(2)): Promise<void> {
  const banner =
    '// AUTO-GENERATED by scripts/generate-web-embed.ts. Do not edit by hand.\n' +
    '// Regenerate with: bun scripts/generate-web-embed.ts (after `bun run web:build`).\n' +
    '//\n' +
    '// Each entry imports a file with `with { type: "file" }` so Bun embeds the\n' +
    '// bytes into the compiled binary; `file` is a runtime-resolvable path that\n' +
    '// Bun.file() can read both in dev and inside the single-file executable.\n' +
    '//\n' +
    '// The committed version is intentionally EMPTY: hashed asset names only exist\n' +
    '// after a web build, so a populated manifest would break fresh checkouts and\n' +
    '// `tsc`. build-release.ts populates it right before the compile step, then\n' +
    '// resets it to empty (`--empty`) so the working tree stays clean.\n\n';

  // --empty: write the committed (empty) form regardless of web/dist contents.
  if (argv.includes('--empty')) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] wrote empty manifest (--empty)\n`);
    return;
  }

  if (!existsSync(DIST_DIR) || !(await stat(DIST_DIR)).isDirectory()) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] web/dist not found — wrote empty manifest\n`);
    return;
  }

  const allFiles = (await walk(DIST_DIR)).sort();
  if (allFiles.length === 0) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] web/dist empty — wrote empty manifest\n`);
    return;
  }

  // REL-03: hard-fail if sourcemaps exist in dist (channel release must not ship them).
  // Vite production has sourcemap:false; a .map here means config drift.
  if (hasSourcemapFiles(allFiles)) {
    const maps = allFiles.filter((f) => extname(f).toLowerCase() === '.map');
    process.stderr.write(
      `[generate-web-embed] REFUSING: found ${maps.length} sourcemap file(s) under web/dist.\n` +
        `  Vite production sourcemaps must stay off (web/vite.config.ts sourcemap: false).\n` +
        maps
          .slice(0, 10)
          .map((m) => `  - ${relative(DIST_DIR, m)}`)
          .join('\n') +
        (maps.length > 10 ? `\n  … +${maps.length - 10} more` : '') +
        '\n',
    );
    process.exit(1);
  }

  const files = allFiles.filter((f) => shouldEmbedAsset(f, DIST_DIR));
  const skipped = allFiles.length - files.length;
  if (skipped > 0) {
    process.stdout.write(
      `[generate-web-embed] skipped ${skipped} non-embeddable file(s) (dotfiles / disallowed ext)\n`,
    );
  }

  if (files.length === 0) {
    await writeFile(OUT_FILE, banner + EMPTY_MANIFEST_BODY);
    process.stdout.write(`[generate-web-embed] nothing allowlisted to embed — wrote empty manifest\n`);
    return;
  }

  const importLines: string[] = [];
  const entryLines: string[] = [];
  files.forEach((f, i) => {
    const spec = toImportSpecifier(f);
    const route = toRoute(f);
    importLines.push(`import _a${i} from ${JSON.stringify(spec)} with { type: 'file' };`);
    entryLines.push(`  { route: ${JSON.stringify(route)}, file: _a${i} },`);
  });

  const out =
    banner +
    importLines.join('\n') +
    '\n\n' +
    'export interface EmbeddedAsset { route: string; file: string }\n\n' +
    'export const embeddedAssets: EmbeddedAsset[] = [\n' +
    entryLines.join('\n') +
    '\n];\n';

  await writeFile(OUT_FILE, out);
  process.stdout.write(
    `[generate-web-embed] embedded ${files.length} file(s) from web/dist -> server/web-assets.generated.ts\n`,
  );
}

if (import.meta.main) {
  main().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`generate-web-embed failed: ${msg}\n`);
    process.exit(1);
  });
}
